[package]
name = "charter-core"
version = "0.1.0"
edition = "2024"

[dependencies]
fmt = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
serde_json_canonicalizer = "0.3.1"
sha2 = "0.10.9"
strum = { version = "0.27.2", features = ["derive"] }
